autoscaling:
  enabled: true
  # initialScale: ...
  # maxScale: ...
  # metric: ...
  # minScale: ...
  # scaleDownDelay: ...
  # scaleToZeroPodRetentionPeriod: ...
  # target: ...
bitstreams:
  intel/ofs_ia420fr0/06dd1e32478657c38c353dc048cdb7e0: com/inaccel/klib/sw/2.0/1align
  intel/ofs_ia840fr0/18f573d96298516d891fc9b6261e3a73: com/inaccel/klib/sw/2.0/1align
  intel/pac_a10/38d782e3b6125343b9342433e348ac4c: com/inaccel/klib/sw/2.0/1align
  intel/pac_s10/9346116da52d5ca8b06aa9a389ef7c8d: com/inaccel/klib/sw/2.0/1align
# cpu: ...
env:
  WEB_CONCURRENCY: 1
fpga: 1
image: inaccel/marketplace
# memory: ...
# platform: ...
pullPolicy: Always
# pullSecret: ...
tag: smith-waterman
# replicas: ...
