---
apiVersion: v1
kind: Secret
metadata:
  {{- if $.Values.credentials }}
  annotations:
    {{- if $.Values.credentials.s3 }}
    {{- if $.Values.credentials.s3.region }}
    serving.kserve.io/s3-region: {{ $.Values.credentials.s3.region }}
    {{- end }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "labels" $ | nindent 4 }}
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
{{- if $.Values.credentials }}
stringData:
  {{- if $.Values.credentials.databricks }}
  {{- if $.Values.credentials.databricks.host }}
  DATABRICKS_HOST: {{ $.Values.credentials.databricks.host }}
  {{- end }}
  {{- if $.Values.credentials.databricks.insecure }}
  DATABRICKS_INSECURE: {{ $.Values.credentials.databricks.insecure }}
  {{- end }}
  {{- if $.Values.credentials.databricks.password }}
  DATABRICKS_PASSWORD: {{ $.Values.credentials.databricks.password }}
  {{- end }}
  {{- if $.Values.credentials.databricks.token }}
  DATABRICKS_TOKEN: {{ $.Values.credentials.databricks.token }}
  {{- end }}
  {{- if $.Values.credentials.databricks.username }}
  DATABRICKS_USERNAME: {{ $.Values.credentials.databricks.username }}
  {{- end }}
  MLFLOW_TRACKING_URI: databricks
  {{- end }}
  {{- if $.Values.credentials.mlflow }}
  {{- if $.Values.credentials.mlflow.trackingInsecureTls }}
  MLFLOW_TRACKING_INSECURE_TLS: {{ $.Values.credentials.mlflow.trackingInsecureTls }}
  {{- end }}
  {{- if $.Values.credentials.mlflow.trackingPassword }}
  MLFLOW_TRACKING_PASSWORD: {{ $.Values.credentials.mlflow.trackingPassword }}
  {{- end }}
  {{- if $.Values.credentials.mlflow.trackingToken }}
  MLFLOW_TRACKING_TOKEN: {{ $.Values.credentials.mlflow.trackingToken }}
  {{- end }}
  {{- if $.Values.credentials.mlflow.trackingUri }}
  MLFLOW_TRACKING_URI: {{ $.Values.credentials.mlflow.trackingUri }}
  {{- end }}
  {{- if $.Values.credentials.mlflow.trackingUsername }}
  MLFLOW_TRACKING_USERNAME: {{ $.Values.credentials.mlflow.trackingUsername }}
  {{- end }}
  {{- end }}
  {{- if $.Values.credentials.s3 }}
  {{- if $.Values.credentials.s3.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ $.Values.credentials.s3.accessKeyId }}
  {{- end }}
  {{- if $.Values.credentials.s3.region }}
  AWS_DEFAULT_REGION: {{ $.Values.credentials.s3.region }}
  {{- end }}
  {{- if $.Values.credentials.s3.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.credentials.s3.secretAccessKey }}
  {{- end }}
  {{- end }}
{{- end }}
type: Opaque
